# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lf7vHiGPKiv6imPZ47oYva-98lLJG6qr
"""

# train_model.py

import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.datasets import imdb

# Load IMDB data
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=20000)

# Pad sequences to the same length for consistency in model input
max_length = 100
X_train = pad_sequences(X_train, maxlen=max_length)
X_test = pad_sequences(X_test, maxlen=max_length)

# Build the LSTM model
model = Sequential()
model.add(Embedding(20000, 128, input_length=max_length))  # Embedding layer
model.add(LSTM(60, activation='tanh'))  # LSTM layer
model.add(Dropout(0.5))  # Dropout to reduce overfitting
model.add(Dense(1, activation='sigmoid'))  # Output layer (binary classification)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, batch_size=128, validation_data=(X_test, y_test))

# Save the trained model
model.save('sentiment_model.h5')
print("Model saved as sentiment_model.h5")